# Generated by Django 5.1.4 on 2024-12-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_remove_expense_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
