# Generated by Django 5.1.4 on 2025-01-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_income_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
    ]
